### ISSUE TITLE
💬 Discussion: No plan for #Hacktoberfest ? 🚀

### ISSUE THREAD

**Issue by shaonkabir8** [gatsbyjs/gatsby-bn#30]
Hi 👋 
`October` ia almost at very ending 😞 
No plans for `Hacktoberfest` ? Seriously?! 😕 
Even most of the `gatsby` repos are participating  in this Hacking ❤️ why not we?  😕

**Comment by shakib609** [comment]
`hacktoberfest` tag added. Thanks for the reminder. Hopefully, we'll see more contributions because of this.
